

service: wishlist-practice

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.7
  versionFunctions: false
  environment:
    dbname: df0cibdp5db9f
    user: ${opt:user}
    password: ${opt:password}
    host: ec2-174-129-210-249.compute-1.amazonaws.com
    port: 5432

functions:
  hello:
    handler: handler.hello
    events: 
      - http:
          path: users/create
          method: get
  
  claimGift:
    handler: functions/wishlist_handler.claim_gift
    events: 
      - http:
          path: claim/{id}
          method: post
  
  listGifts:
    handler: functions/wishlist_handler.list_gifts
    events:
      - http:
          path: list
          method: get


