

service: wishlist-practice

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.7
  versionFunctions: false
  environment:
    dbname: df0cibdp5db9f
    user: ${opt:user}
    password: ${opt:password}
    host: ec2-174-129-210-249.compute-1.amazonaws.com
    port: 5432

functions:

  listLists:
    handler: functions/list_handler.list_lists
    events: 
      - http:
          path: user/{user_id}/lists
          method: get
  
  addList:
    handler: functions/list_handler.put_list
    events: 
      - http:
          path: user/{user_id}/list
          method: post

  updateList:
    handler: functions/list_handler.put_list
    events: 
      - http:
          path: user/{user_id}/list/{list_id}
          method: put

  addGuest:
    handler: functions/list_handler.put_list
    events: 
      - http:
          path: user/{user_id}/list/{list_id}
          method: post

  removeGuest:
    handler: functions/list_handler.delete_guest
    events: 
      - http:
          path: user/{user_id}/list/{list_id}
          method: delete